language: ruby
cache: bundler
gemfile:
  - gemfiles/jekyll_v2.gemfile
  - gemfiles/jekyll_v3.gemfile
before_script: bundle update
script: ./scripts/test_ci
rvm:
 - 2.4
 - 2.3
 - 2.2
 - 2.1
 - 2.0
notifications:
  email:
    on_success: never
    on_failure: never
